### ISSUE TITLE
Demo broken

### ISSUE THREAD

**Issue by awethentik** [mtr/core-layout#12]
Uncaught ReferenceError: _ is not defined
bundle.js:11540 Uncaught Error: [$injector:modulerr] Failed to instantiate module myApp due to:
Error: [$injector:nomod] Module 'myApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.15/$injector/nomod?p0=myApp
    at https://mtr.github.io/core-layout/examples/js/bundle.js:7465:12
    at https://mtr.github.io/core-layout/examples/js/bundle.js:9176:17
    at ensure (https://mtr.github.io/core-layout/examples/js/bundle.js:9100:38)
    at module (https://mtr.github.io/core-layout/examples/js/bundle.js:9174:14)
    at https://mtr.github.io/core-layout/examples/js/bundle.js:11517:22
    at forEach (https://mtr.github.io/core-layout/examples/js/bundle.js:7725:20)
    at loadModules (https://mtr.github.io/core-layout/examples/js/bundle.js:11501:5)
    at createInjector (https://mtr.github.io/core-layout/examples/js/bundle.js:11427:11)
    at doBootstrap (https://mtr.github.io/core-layout/examples/js/bundle.js:8854:20)
    at bootstrap (https://mtr.github.io/core-layout/examples/js/bundle.js:8875:12)
http://errors.angularjs.org/1.3.15/$injector/modulerr?p0=myApp&p1=Error%3A%…A%2F%2Fmtr.github.io%2Fcore-layout%2Fexamples%2Fjs%2Fbundle.js%3A8875%3A12)

**Comment by mtr** [comment]
Thank you, @awethentik for reporting this.  The reason was that I had forgotten to update the angular-iscroll dependency version.
